### ISSUE TITLE
Does IL Repack remove unused members?

### ISSUE THREAD

**Issue by TonyValenti** [gluck/il-repack#295] opened 2021-07-08 11:07 UTC
If I use IL Repack, is there an option to only include types that are used instead of the whole assembly?

**Comment by ngyukman** [comment] 2021-08-10 02:37
iirc, I don't think there is such an option for that

**Comment by gluck** [comment] 2021-08-16 11:57
IIRC if you internalize types, it'l only merged the types which as used:
e.g. `ILRepack A.dll B.dll /intern` will only expose A types and include B types used by A.

**Comment by KirillOsenkov** [comment] 2024-01-07 03:18
Duplicate of #309

**Closed by KirillOsenkov** 2024-01-07 03:18 UTC
