### ISSUE TITLE
Merge C++/CLI assemblies

### ISSUE THREAD

**Issue by wmjordan** [gluck/il-repack#375] opened 2024-10-05 00:04 UTC
Is it possible to merge those assemblies compiled by C++/CLI compiler?

**Comment by lextm** [comment] 2024-10-05 00:24
Duplicate to #200, if you know C++/CLI produces mixed mode assemblies.

**Comment by KirillOsenkov** [comment] 2024-10-05 00:25
duplicate of #200

**Closed by KirillOsenkov** 2024-10-05 00:25 UTC
