### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by biz0n** [gluck/il-repack#96] opened 2015-05-20 13:29 UTC
```
...
INFO: - Importing System.Reactive.Strings_PlatformServices.resources
INFO: - Resource 'WINRT_NO_SUB1MS_TIMERS' (type: ResourceTypeCode.String)
INFO: Fixing references
System.NullReferenceException: Object reference not set to an instance of an object
  at Mono.Cecil.ParameterDefinition.get_CustomAttributes () [0x00000] in <filename unknown>:0 
  at ILRepacking.ReferenceFixator.FixReferences (Mono.Cecil.ParameterDefinition definition) [0x00000] in <filename unknown>:0 
  at ILRepacking.ReferenceFixator.FixReferences (Mono.Collections.Generic.Collection``1 parameters) [0x00000] in <filename unknown>:0 
  at ILRepacking.ReferenceFixator.Fix (Mono.Cecil.MethodReference method) [0x00000] in <filename unknown>:0 
  at ILRepacking.ReferenceFixator.FixReferences (Mono.Cecil.Cil.Instruction instr) [0x00000] in <filename unknown>:0 
  at ILRepacking.ReferenceFixator.FixReferences (Mono.Cecil.Cil.MethodBody body) [0x00000] in <filename unknown>:0 
  at ILRepacking.ReferenceFixator.FixReferences (Mono.Cecil.MethodDefinition meth) [0x00000] in <filename unknown>:0 
  at ILRepacking.ReferenceFixator.FixReferences (Mono.Cecil.TypeDefinition type) [0x00000] in <filename unknown>:0 
  at ILRepacking.Steps.ReferencesFixStep.Perform () [0x00000] in <filename unknown>:0 
  at ILRepacking.ILRepack.Repack () [0x00000] in <filename unknown>:0 
  at ILRepacking.Application.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

Catch this exception when I try to merge Rx (files in [zip](https://dl.dropboxusercontent.com/u/13193316/repro.zip))

command:
`mono ILMerge.exe /targetplatform:v4,,/Library/Frameworks/Mono.framework/Versions/4.0.0/lib/mono/4.5 /out:test.dll System.Reactive.Core.dll System.Reactive.Interfaces.dll`

OS: Mac OS X 10.10.3

**Comment by gluck** [comment] 2015-05-20 22:08
I can't manage to reproduce on latest (and on windows).
May be linked to mon and the fact that its fwk folder includes Rx, not sure.

**Comment by biz0n** [comment] 2015-05-21 17:44
I can't merge all [Rx](https://dl.dropboxusercontent.com/u/13193316/Rx.zip) libraries on Mac OS

sometimes catch this exception (if merge System.Reactive.PlatformServices.dll and System.Reactive.Interfaces.dll):

```
System.NullReferenceException: Object reference not set to an instance of an object
  at Mono.Cecil.Cil.CodeWriter.ComputeStackDelta (Mono.Cecil.Cil.Instruction instruction, System.Int32& stack_size) [0x0007d] in /Users/grigoryp/Documents/il-repack/cecil/Mono.Cecil.Cil/CodeWriter.cs:419 
  at Mono.Cecil.Cil.CodeWriter.ComputeStackSize (Mono.Cecil.Cil.Instruction instruction, System.Collections.Generic.Dictionary`2& stack_sizes, System.Int32& stack_size, System.Int32& max_stack) [0x00027] in /Users/grigoryp/Documents/il-repack/cecil/Mono.Cecil.Cil/CodeWriter.cs:353 
  at Mono.Cecil.Cil.CodeWriter.ComputeHeader () [0x00067] in /Users/grigoryp/Documents/il-repack/cecil/Mono.Cecil.Cil/CodeWriter.cs:309 
  at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody (Mono.Cecil.MethodDefinition method) [0x0000e] in /Users/grigoryp/Documents/il-repack/cecil/Mono.Cecil.Cil/CodeWriter.cs:108 
  at Mono.Cecil.Cil.CodeWriter.WriteMethodBody (Mono.Cecil.MethodDefinition method) [0x0004d] in /Users/grigoryp/Documents/il-repack/cecil/Mono.Cecil.Cil/CodeWriter.cs:56 
  at Mono.Cecil.MetadataBuilder.AddMethod (Mono.Cecil.MethodDefinition method) [0x00019] in /Users/grigoryp/Documents/il-repack/cecil/Mono.Cecil/AssemblyWriter.cs:1402 
  at Mono.Cecil.MetadataBuilder.AddMethods (Mono.Cecil.TypeDefinition type) [0x00017] in /Users/grigoryp/Documents/il-repack/cecil/Mono.Cecil/AssemblyWriter.cs:1396 
  at Mono.Cecil.MetadataBuilder.AddType (Mono.Cecil.TypeDefinition type) [0x000ad] in /Users/grigoryp/Documents/il-repack/cecil/Mono.Cecil/AssemblyWriter.cs:1231 
  at Mono.Cecil.MetadataBuilder.AddTypeDefs () [0x0001c] in /Users/grigoryp/Documents/il-repack/cecil/Mono.Cecil/AssemblyWriter.cs:1205 
  at Mono.Cecil.MetadataBuilder.BuildTypes () [0x0001d] in /Users/grigoryp/Documents/il-repack/cecil/Mono.Cecil/AssemblyWriter.cs:1050 
  at Mono.Cecil.MetadataBuilder.BuildModule () [0x00091] in /Users/grigoryp/Documents/il-repack/cecil/Mono.Cecil/AssemblyWriter.cs:832 
  at Mono.Cecil.MetadataBuilder.BuildMetadata () [0x00002] in /Users/grigoryp/Documents/il-repack/cecil/Mono.Cecil/AssemblyWriter.cs:805 
  at Mono.Cecil.ModuleWriter.BuildMetadata (Mono.Cecil.ModuleDefinition module, Mono.Cecil.MetadataBuilder metadata) [0x0000e] in /Users/grigoryp/Documents/il-repack/cecil/Mono.Cecil/AssemblyWriter.cs:110 
  at Mono.Cecil.ModuleWriter.WriteModuleTo (Mono.Cecil.ModuleDefinition module, System.IO.Stream stream, Mono.Cecil.WriterParameters parameters) [0x000cc] in /Users/grigoryp/Documents/il-repack/cecil/Mono.Cecil/AssemblyWriter.cs:90 
  at Mono.Cecil.ModuleDefinition.Write (System.IO.Stream stream, Mono.Cecil.WriterParameters parameters) [0x0002c] in /Users/grigoryp/Documents/il-repack/cecil/Mono.Cecil/ModuleDefinition.cs:1092 
  at Mono.Cecil.ModuleDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters) [0x0000f] in /Users/grigoryp/Documents/il-repack/cecil/Mono.Cecil/ModuleDefinition.cs:1081 
  at Mono.Cecil.AssemblyDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters) [0x00009] in /Users/grigory
```

**Comment by timotei** [comment] 2015-05-24 21:00
A bit on investigation reveals the following (for the first case/original exception in this issue):

The exception happens when fixing method "OnNext" in DeclaringType = **{System.Reactive.IObserver`2<T,TResult>}**, more specifically, its first parameter (which is of type  **{System.Reactive.IObserver`2/!0}**)

Now, in ReferenceFixator:92, we do ```return ((TypeDefinition)type.DeclaringType).NestedTypes.FirstOrDefault(x => x.FullName == type.FullName);```, which actually yields null, because **IObserver`2** doesn't have any NestedTypes.

Shouldn't we first check that we have nested types before doing that?

**Comment by timotei** [comment] 2015-05-29 20:52
A quick update. 

More investigation. The method which triggers the error is from `System.Reactive.Notification<T>`, subclass: ```OnNextNotification : Notification<T>```:

			public override TResult Accept<TResult>(IObserver<T, TResult> observer)
			{
				if (observer == null)
				{
					throw new ArgumentNullException("observer");
				}
				return observer.OnNext(this.Value);
			}

and trying to fix the instruction part of the return:

```instr	{IL_0000: callvirt System.Reactive.IObserver`2/!1 System.Reactive.IObserver`2<T,TResult>::OnNext(System.Reactive.IObserver`2/!0)}	Mono.Cecil.Cil.Instruction```

It seems that on windows, the generic type (TResult I think - ```!1```) does *not* have a DeclaringType, while on unix it has: ```System.Reactive.IObserver`2```

**Comment by timotei** [comment] 2015-05-30 16:43
@gluck You were right, it seems to be because we've already got RX (though version 2.2.0 - not 2.2.5 which is merged here) on the mono platform dir.

Now, this brings a question: Why do we need to get the platform libs? A possible fix which is IMO a very good candidate, is to *not* resolve platform libs if the file is specified in the list of assemblies to merge (if we want to merge a specific version of a library - in our case reactive - we shouldn't exchange that with the framework bundled one). What do you think?

I've looked at the history of the file by @goldsimon (https://github.com/gluck/il-repack/commit/3e502f67c64f4553c4357d3b5467baf41ec75d6d#diff-cafc6879862c32bfe0ffe9dea3e20600), but couldn't figure exactly why that is needed.

Btw, if you want to reproduce this on windows, you can put the two files in C:\Windows\Microsoft .NET\v4...\ (https://dl.dropboxusercontent.com/u/462510/tmp/system_reactive_2.2.0.zip), and then just add the ```/targetplatform:v4``` as arg and you should get the exception. I'll keep looking into the actually issue though, because even in 2.2.0 the ```IObserver`2``` has not changed..

@biz0n If I specify the "/Facades" suffix on the path (so the command would be: ```mono ILRepack.exe /targetplatform:v4,,/Library/Frameworks/Mono.framework/Versions/4.0.0/lib/mono/4.5/Facades /out:test.dll System.Reactive.Core.dll System.Reactive.Interfaces.dll``` it works just fine, but not sure the end result is working. Maybe you can check with your target application?

**Comment by timotei** [comment] 2015-05-30 17:32
OK, I think I've found the *actual* problem and fixed it properly.

In https://github.com/gluck/il-repack/blob/master/ILRepack/PlatformFixer.cs#L154 it seems we don't properly handle GenericParameter (which !0 and !1 are!), and instead, we create a TypeReference instead of a GenericParameter how it should be. If we create a GenericParameter, everything seems to be fine. I'll come back with a PR because it needs some Cecil enhancement (in order to properly construct a new GenericParameter)

**Closed** 2015-06-07 22:49 UTC
Labels: bug
