### ISSUE TITLE
Merging assemblies with a reference to Autofac

### ISSUE THREAD

**Issue by mauricedb** [gluck/il-repack#58] opened 2014-04-30 09:38 UTC
I am trying to ILMerge a project containing Autofac.dll and that fails on that dependency.

The command I am using is: `ILRepack.exe /out:Merged.exe ILRepackTest.exe Autofac.dll`

## Expected outcome ##
To have ILRepackTest.exe and Autofac.dll to be merged to Merged.exe

## Observed output is the following exception: ##
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.ModuleDefinition.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at ILRepacking.ReferenceFixator.FixReferences(Collection`1 attributes)
   at ILRepacking.ReferenceFixator.FixReferences(MethodDefinition meth)
   at ILRepacking.ReferenceFixator.FixReferences(TypeDefinition type)
   at ILRepacking.ILRepack.Repack()
   at ILRepacking.ILRepack.Main(String[] args)

### Note ###
My understanding is this is because Autofac is created as a portable class library. See https://github.com/autofac/Autofac/wiki/Frequently-Asked-Questions

**Comment by dennisdoomen** [comment] 2015-04-20 06:18
Unfortunately this still doesn't work. Just try to merge a .NET 4.5 assembly with Autofac and the same problem with `System.Core` appears.

**Comment by carstenschuette** [comment] 2015-05-17 16:00
Problem still there with ILRepack 1.26

**Comment by gluck** [comment] 2015-05-17 16:40
Strange, there's now a passing test that round trips Autofac net45 assembly (with no error).
Do you have an easy reproduction path ? (ideally that would be the merge of a set of dlls available from NuGet packages)

**Comment by dennisdoomen** [comment] 2015-05-17 18:09
Yes, just merge a DLL that references Autofac and then try to merge that one in another .DLL that also references Autofac, preferably a different version.

**Comment by carstenschuette** [comment] 2015-05-17 19:42
This also happens without Autofac. It seems to be a problem with Assemblies from .net 4.5. I have a simple application that references System.Core and several Azure Management assemblies.

**Comment by gluck** [comment] 2015-05-18 06:33
If someone can provide the simplest project or assembly that causes this when merged, I can have a look.
Autofac NuGet package only has a net40 dll and a portable-win+net40+sl50+wp8 one, tests are running with the former only so far.

**Comment by biz0n** [comment] 2015-05-18 17:07
I am trying to ILMerge a libraries from [zip](https://db.tt/JjS3WMRZ) archive
The command I am using is: 
`mono ILRepack.exe /targetversion:v4 /out:test.dll Autofac.dll Nitro.Async.dll`

**Closed** 2015-06-07 22:49 UTC
Labels: bug

**Comment by SarahBourgeois** [comment] 2017-08-16 20:58
specify the path of your dll in the command line 
`ILRepack.exe /out:Merged.exe ILRepackTest.exe C:\My_dll_Path\Autofac.dll`
